meta-llama/llama-stack-apps

llama_agentic_system/server.py

The way a config updater was implemented is deprecated. I replaced the `on_event` with `lifespan`, the latest method. Please take a look at this [reference](https://fastapi.tiangolo.com/advanced/events/).

Replace deprecated method of FastAPI

---

README.md

1. and extra $ sign was there which caused problem if someone directly copies it
2. it is local-ollama not ollama-local

Fixed a command in readme for ollama instructions

---

README.md

The distribution was called `ollama-local` in the README.md but it is actually called `local-ollama` in the CLI, so, I think it is better to use the same naming everywhere.

Update README.md replaced ollama-local by local-ollama

---

sdk_examples/safety/client.py

- Safety API added in: https://github.com/meta-llama/llama-stack/pull/62
- more instructions here: https://github.com/meta-llama/llama-stack/blob/main/docs/cli_reference.md
```
$ python sdk_examples/safety/client.py localhost 5000
SafetyRunShieldsResponse(responses=[SheidResponse(is_violation=False, shield_type='llama_guard', violation_return_message=None, violation_type=None)])
SafetyRunShieldsResponse(responses=[SheidResponse(is_violation=True, shield_type='llama_guard', violation_return_message="I can't answer that. Can I help with something else?", violation_type='S9')])
```

add script for running Safety example via SDK

---

common/execute_with_custom_tools.py

If you check in the file execute_with_custom_tools.py in the execute_turn method, in the end of the method we assign next_message to current_message and next_message is result_message which is a list of ToolResponseMessage but the execute_turn method allows only UserMessage in the messages argument, Hence this change.

Added ToolResponseMessage in messages list for execute_turn method

---

examples/agents/inflation.py

TickerDataTool is not used in inflation.py file.

Remove unused import of TickerDataTool

---

README.md

Seeing an error when running using path: 
```
PYTHONPATH=. python examples/agents/rag_with_memory_bank.py localhost 5000
Traceback (most recent call last):
File "/home/dineshyv/local/llama-stack-apps/examples/agents/rag_with_memory_bank.py", line 19, in <module>
from .multi_turn import execute_turns, prompt_to_turn
ImportError: attempted relative import with no known parent package
```

fix run command for agent example in README

---

README.md

The "Getting Started Guide" URL in the README.md had a [broken URL](https://llama-stack.readthedocs.io/en/doc-simplify/getting_started/index.html)
I changed the URL to point to [this documentation page](https://llama-stack.readthedocs.io/en/latest/getting_started/index.html) which covers starting and running a Llama Stack Server

Fix Incorrect URL in README.md

---

examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/MessageAdapter.java

Fixing a bug where getRecentSavedTextMessages() would only get CONVERSATION_HISTORY_MESSAGE_LOOKBACK - 1. Now with this fix, function will retrieve CONVERSATION_HISTORY_MESSAGE_LOOKBACK # of conversations. 
1. Tested with Llama 3.2 3B and confirmed with logs

[Android App] Bug fix in getting recent messages

---

examples/agent_store/api.py

Summary:
Ran the command only to find all-MiniLM-L6-v2 is being selected by default.
```
python -m examples.agent_store.app localhost 5000
Using model: all-MiniLM-L6-v2
* Running on local URL:  http://0.0.0.0:7860
```
Test Plan:
Run the command with the change and validate that meta-llama/Llama-3.2-3B-Instruct is used instead
```
python -m examples.agent_store.app localhost 5000
Using model: meta-llama/Llama-3.2-3B-Instruct
* Running on local URL:  http://0.0.0.0:7860
```

Fix default model for agent store app

---

examples/ios_calendar_assistant/README.md
examples/ios_calendar_assistant/iOSCalendarAssistantWithLocalInf/ContentView.swift
examples/ios_quick_demo/README.md
examples/ios_quick_demo/iOSQuickDemo/iOSQuickDemo/ContentView.swift

To work with the updated LocalInferenceImpl  [here](https://github.com/meta-llama/llama-stack/pull/911).

update for local inference demo for LS 0.1

---

README.md

Closes #168
Docfix
The [LlamaStack quickstart](https://llama-stack.readthedocs.io/en/latest/getting_started/index.html) uses port 8321.

Update README directions to match llama-stack repository README directions for server port

---

examples/ios_calendar_assistant/README.md
examples/ios_calendar_assistant/iOSCalendarAssistant/ContentView.swift
examples/ios_quick_demo/README.md
examples/ios_quick_demo/iOSQuickDemo/iOSQuickDemo/ContentView.swift

Updated demo for Llama Stack 0.1.3 ([release](https://github.com/meta-llama/llama-stack/releases/tag/v0.1.3) and [spec](https://github.com/meta-llama/llama-stack/blob/main/docs/_static/llama-stack-spec.html)). 
Need to use the updated iOS Swift SDK [here](https://github.com/meta-llama/llama-stack-client-swift/pull/20) to build and run.

update iOS demos for LS0.1.3

---

requirements.txt

See https://github.com/ranaroussi/yfinance/pull/2277 and https://github.com/ranaroussi/yfinance/issues/2276. 
Getting very frequent rate limiting issue since yesterday:
```
1 Failed download:
['GOOG']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
```

Require yfinance >= 0.2.54 to avoid rate limiting issue

---

examples/agents/rag_with_vector_db.py

Summary:
so that rerunning the example doesn't keep adding to the same db
Test Plan:
python -m examples.agents.rag_with_vector_db localhost 5001

feat: use uuid4 for vector_db_id in example

---

examples/agents/react_agent.py

This is to be consistent with other examples.

fix: Allows users to configure host/port in react agent example

---

examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/ExampleLlamaStackRemoteInference.kt

Previously, the method fails for google pixel phones, most likely due to how the URI is constructed and having the different format, hence resulting in cursor moveToFirst() is null.. In that case, I found a more robust way to do it that also works for pixel phones.
Ensure that image reasoning works for multiple Android phones

Fix kotlin getFilePathFromUri() for Images

---

examples/agents/react_agent.py

This PR adds `provider_data={"tavily_search_api_key": os.getenv("TAVILY_SEARCH_API_KEY")}` to the client definition in examples/agents/react_agent.py. Without it, users can get the following error if they have not previously added the provider data to their server:
```
llama_stack_client.BadRequestError: Error code: 400 - {'detail': 'Invalid value: Pass Search provider\'s API Key in the header X-LlamaStack-Provider-Data as { "tavily_search_api_key": <your api key>}'}
```
I started a fresh Llama Stack server and ran examples/agents/react_agent.py as is, and I received the error above. 
I started a fresh Llama Stack server and ran examples/agents/react_agent.py with the changes in this PR and the example ran as expected. 
Thanks for …

fix: react_agent.py needs tavily_search_api_key

---

examples/ios_calendar_assistant/iOSCalendarAssistantWithLocalInf.xcodeproj/project.pbxproj

This PR cleans-up the project dependency within the iOSCalendarAssitantWithLocalInf:
- Add LlamaStackClient (Swift SDK) project dependency
- Remove ExecuTorch dependency. As a result, remove the force-loading of the backends which causes re-registering issues. ExecuTorch will now be sourced from the Swift SDK only. This is be improved even further.
- Maintain reference dummy files for tokenizer, model pte, and Swift SDK project. This can also be improved further.
Overall, this was part of the effort to be able to update the ExecuTorch module in the Swift SDK ([PR](https://github.com/meta-llama/llama-stack-client-swift/pull/27)).
This has been tested with the [iOSCalendarAssistantWithLocaInfr project](https://github.com/meta-llama/llama-stack-apps/tree/main/examples/ios_calendar_assistant) …

Clean-up iOSCalendarAssitantWithLocalInf Project Dependencies

---

examples/agents/rag_as_attachments.py

- Update script since https://github.com/meta-llama/llama-stack/pull/1763 no longer requires knowledge search tool for attachments. 
```
python -m examples.agents.rag_as_attachments localhost 8321
```

update rag as attachment script

---

examples/interior_design_assistant/generate_descriptions.py

Fix typo in `examples/interior_design_assistant/generate_descriptions.py`.

Fix typo in generate_descriptions.py
