meta-llama/llama-stack-apps

llama_agentic_system/system_prompt.py

I'm guessing that the "a" is likely a typo.

Remove unintentional article

---

README.md

Added installation guide via Python virtual environment

Added installation guide via Python virtual environment

---

tests/test_e2e.py

Updated e2e tests with the json based tool call format. 
Corresponding PRs in llama-models ( update cli ) and llama-toolchain ( update agentic_system provider )
- https://github.com/meta-llama/llama-stack/pull/29
- https://github.com/meta-llama/llama-models/pull/110
Tested with 
```
llama distribution start --name hhh 
python -m unittest tests.test_e2e.TestE2E -v
```

Updated e2e tests to reflect new json tool call format

---

sdk_examples/README.md
sdk_examples/agentic_system/client.py
sdk_examples/inference/client.py

As per https://github.com/meta-llama/llama-stack/pull/58#discussion_r1750798368, adding client SDK scripts. 
https://github.com/user-attachments/assets/a7fe2811-5d79-4db0-aa99-bd858a0bbc56

add SDK example client scripts

---

requirements.txt

- PyPi package built at: https://pypi.org/project/llama-stack/ via https://github.com/fairinternal/llama-stack-python
```
pip install llama-stack
```
```
python sdk_examples/agentic_system/client.py devgpu004.eag5.facebook.com 5001
python sdk_examples/inference/client.py devgpu004.eag5.facebook.com 5001
```

udpate requirements with llama-stack pypi package

---

sdk_examples/agentic_system/client.py
sdk_examples/inference/client.py
sdk_examples/safety/client.py

- Using updated API spec & server endpoints in https://github.com/meta-llama/llama-stack/pull/64
```
python sdk_examples/inference/client.py localhost 5000
python sdk_examples/safety/client.py localhost 5000
python sdk_examples/agentic_system/client.py localhost 5000
```

Update client scripts with updated SDK

---

README.md
requirements.txt
sdk_examples/README.md
sdk_examples/agentic_system/client.py

- update agentic_system SDK example with tool calling & parsing
- update readme in `sdk_examples`
```
python sdk_examples/agentic_system/client.py localhost 6001
```

Update SDK examples

---

sdk_examples/agents/client.py
sdk_examples/inference/client.py
sdk_examples/memory/client.py
sdk_examples/safety/client.py

✅  inference
✅  safety
✅  memory
✅  agents
✅   models
✅   shields
✅   memory_banks

[API Updates 3]api_updates_3 SDK fix

---

examples/agents/client.py

One of the keys inside agent_config object is wrong in the examples/agents/client.py file. The key there is tool_choices but it should be tool_choice. This push is for that purpose

Corrected agent config key

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/PULL_REQUEST_TEMPLATE.md
examples/interior_design_assistant/README.md
examples/interior_design_assistant/generate_descriptions.py

Closes #97 & #99
1. corrected imports for generate_description.py
2. enhanced readme 
3. added templates for improved github workflow
ran
```
PYTHONPATH=. python examples/interior_design_assistant/api.py localhost 5000 examples/interior_design_assistant/resources/documents/ examples/interior_design_assistant/resources/images/fireplaces
```
Output:

Interior app refactor & github templates

---

examples/eval/client.py
examples/scoring/client.py
examples/scoring/resources/test_dataset.csv

- Add example demo scripts for using evals API. 
```
python -m examples.scoring.client $LOCALHOST 5000 ./examples/scoring/resources/test_dataset.csv
```
```
python -m examples.eval.client $LOCALHOST 5000 ./examples/scoring/resources/test_dataset.csv
```
See: https://github.com/meta-llama/llama-stack/pull/333

[Evals API] eval client demo scripts

---

examples/agents/client.py

Add HTTPS client example in llama-stack-apps
```
(stack) bchen@dev-modeling:~/llama-stack-apps(main)$ python examples/agents/client.py --host=llamastack-preview.fireworks.ai --port=443 --use_https=True
Created session_id=dbff2ee9-0a0f-4427-bd17-8eeefefa9c45 for Agent(4ddfbacd-f8af-43af-bd60-1feb98440625)
inference> Switzerland is a beautiful country with a rich history, stunning landscapes, and vibrant culture. Here are three must-visit places to add to your itinerary:
1. **Jungfraujoch**: Known as the "Top of Europe," Jungfraujoch is a mountain peak located in the Bernese …
```

[LlamaStack][Client] Add https

---

examples/inference/client.py

This pull request introduces an API-driven approach to dynamically fetch available models from the server, allowing users to select a model at runtime rather than relying on a hardcoded model. The fetched models are listed, and users can choose the model they want to use, improving flexibility and adaptability of the system.
Logs for Test A : Successfully retrieved models, user prompt shows available models, user can select any model dynamically.
Logs for Test B :  If no models are available, the system displays a clear error …

Enable dynamic model selection via API call

---

README.md
examples/agents/client.py
examples/agents/e2e_loop_with_custom_tools.py
examples/agents/hello.py
examples/agents/inflation.py
examples/agents/podcast_transcript.py
examples/agents/rag_as_attachments.py
examples/agents/rag_with_memory_bank.py

1. remove the --disable-safety flag for the examples. 
2.The examples now will check if shield is supported and inject the shields to the `AgentConfig`.
Closes #110  (issue)
- examples.agents.hello
Logs for running the hello case with no shield
```
PYTHONPATH=. python -m examples.agents.hello localhost 5050
No available shields. Disable safety.
inference> How can I assist you today?
inference> brave_search.call(query="NBA Western Conference Semifinals 2024 winning team roster")
tool_execution> Tool:brave_search Args:{'query': 'NBA Western Conference Semifinals 2024 winning …
```

remove the --disable-safety flag

---

examples/agents/client.py
examples/agents/hello.py
examples/agents/inflation.py
examples/agents/podcast_transcript.py
examples/agents/rag_as_attachments.py
examples/agents/rag_with_memory_bank.py
examples/inference/client.py

- fix llama-stack-apps
```
$ llama stack build --template together --image-type conda
$ llama stack run ~/.llama/distributions/llamastack-together/together-run.yaml
```
```
python -m examples.agents.client localhost 5000
python -m examples.agents.hello localhost 5000
python -m examples.agents.inflation localhost 5000
python -m examples.agents.podcast_transcript localhost 5000
python -m examples.agents.rag_as_attachments localhost 5000
python -m examples.agents.rag_with_memory_bank localhost 5000
```

Update apps to work with 0.0.53rc

---

examples/agents/client.py
examples/agents/hello.py
examples/agents/inflation.py
examples/agents/podcast_transcript.py
examples/agents/rag_as_attachments.py
examples/agents/rag_with_memory_bank.py
examples/inference/client.py

- add missing commit from https://github.com/meta-llama/llama-stack-apps/pull/119

error checking models

---

examples/agents/rag_with_memory_bank.py
requirements.txt

fix memory bank issues 
please see below
```
python -m examples.agents.rag_with_memory_bank localhost 5000
memory_retrieval> Retrieved context from banks: ['test_bank'].
====
Here are the retrieved documents for relevant context:
=== START-RETRIEVED-CONTEXT ===
id:num-1; content: conversational data, :func:`~torchtune.datasets.chat_dataset` seems to be a good fit. For any...
>
inference> Here's the complete documentation:
**Fine-tuning Llama with a Prompt Template**
```

quick fixes on memory agent and requirement.txt

---

examples/inference/client.py
examples/inference/client_with_vision.py

- async -> sync from event logger update in SDK

fix inference examples

---

examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/ExampleLlamaStackRemoteInference.kt
examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/MainActivity.java

- 0.0.58 now supports streaming. Updating the app side to support that.
- I am leveraging onStreamReceived() as a callback mechanism to get the data back from SDK to mainActivitiy
https://github.com/user-attachments/assets/8f7c579c-501b-4800-8068-ab58b1f3fa98

Support remote streaming

---

examples/android_app/README.md
examples/android_app/app/build.gradle.kts
examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/ExampleLlamaStackLocalInference.kt
examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/MainActivity.java
examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/Message.java
examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/MessageAdapter.java
examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/ToolCalling.kt

- Add custom tool calling for local inferencing
- Handles multiple custom tool calls (example prompt: "create a calendar event for 5pm today for a dr appointment and another calendar event at 7pm today for a dinner")
- Show "..." when prefill/inferencing is happening 
- Fix in `getRecentSavedTextMessages()` to ignore the temporary empty response 
https://github.com/user-attachments/assets/d6b2fc51-8cd9-47f1-84e1-2fe0d3b57f71

Local custom toolcalling

---

README.md

Fixes broken link and two typos:

doc: Fix agent store broken link and types

---

examples/agents/e2e_loop_with_client_tools.py

I found that the model would hallucinate on the ticker symbol with the current prompt. Update to make it more stable.

improve e2e client tools example

---

examples/android_app/README.md

Update Android README.md on compatible ET version during model export

Update Android README.md on compatible ET version

---

examples/agents/hello.py
examples/agents/react_agent.py

- llama-stack-apps example for ReACT agent
- For details, see https://github.com/meta-llama/llama-stack/discussions/975
```
python -m examples.agents.react_agent
```

feat: ReACT agent example

---

examples/agents/e2e_loop_with_client_tools.py
examples/client_tools/calculator.py

Closes #171
Ran and verified the script works:
`python -m examples.agents.e2e_loop_with_client_tools HOST PORT`
I've run the code segment using `llamastack/distribution-ollama:latest` as my local llamastack server with `meta-llama/Llama-3.2-3B-Instruct` as the inference model. All code segments ran without errors.

feat: Add another custom tool function as an example for users

---

README.md

Signed-off-by: Shreyanand <shanand@redhat.com>
Changes Brave search API key requirement instruction in readme to Tavily search API key requirement. 

Change brave search API key to tavily in README

---

examples/agents/hello.py

hello example missing provider_data for the search api key

---

examples/ios_calendar_assistant/iOSCalendarAssistant/ContentView.swift

Tested with the Swift SDK update: https://github.com/meta-llama/llama-stack-client-swift/pull/21

iOSCalendarAssistant update for LS014

---

examples/android_app/README.md
examples/android_app/app/build.gradle.kts

Update Android demo app to latest Kotlin SDK v0.1.4.1

Update kotlin version

---

.gitmodules
examples/ios_calendar_assistant/README.md
examples/ios_calendar_assistant/iOSCalendarAssistantWithLocalInf/ContentView.swift

Related PRs:
https://github.com/meta-llama/llama-stack-client-swift/pull/22
https://github.com/meta-llama/llama-stack/pull/1265

README and code update for LS 0.1.4 and ET submod move

---

examples/agents/react_agent.py

```bash
python -m examples.agents.react_agent localhost 8321
inference> {"thought": "To find the best place in New York for a pizza slice at 2am, I need to search for 24-hour pizzerias in New York that are known for their pizza slices.", "action": {"tool_name": "web_search", "tool_params": {"query": "best 24-hour pizzerias in New York for pizza slices"}}, "answer": null}
tool_execution> Tool:web_search Response:{"query": "best 24-hour pizzerias in New York for pizza slices", "top_k": [{"title": "Top 10 Best 24 hour pizza Near New York, New York - Yelp", "url": "https://www.yelp.com/search?find_desc=24+hour+pizza&find_loc=New+York,+NY", "content": "Top 10 Best 24 Hour Pizza in New York, NY - February 2025 - Yelp - Nuovo York Pizza, Joe's Pizza, East Village Pizza, John's of Bleecker …
```

use json_response_format=True for react agent

---

examples/android_app/app/src/main/java/com/example/llamastackandroiddemo/ExampleLlamaStackRemoteInference.kt

Modify the agentic system prompt to help when do respond with a normal answer vs tool call.

Modifying Agentic System Prompt

---

examples/agents/rag_as_attachments.py
examples/agents/rag_with_vector_db.py

fix: rag_as_attachments, rag_with_vector_db example

---

examples/DocQA/app.py
examples/agents/e2e_loop_with_client_tools.py
examples/agents/hello.py
examples/agents/inflation.py
examples/agents/podcast_transcript.py
examples/agents/rag_as_attachments.py
examples/agents/rag_with_vector_db.py

Summary:
Test Plan:
run example scripts

chore: update example to use new Agent API

---

examples/agents/react_agent.py

- update to follow api in https://github.com/meta-llama/llama-stack-client-python/pull/189
```
python -m examples.agents.react_agent localhost 8321
```

chore: update react example

---

examples/ios_calendar_assistant/README.md
examples/ios_calendar_assistant/iOSCalendarAssistant.xcodeproj/project.pbxproj
examples/ios_calendar_assistant/iOSCalendarAssistant/ContentView.swift
examples/ios_quick_demo/README.md
examples/ios_quick_demo/iOSQuickDemo/iOSQuickDemo.xcodeproj/project.pbxproj
examples/ios_quick_demo/iOSQuickDemo/iOSQuickDemo/ContentView.swift

Demo app working the latest Together LS server. 
Tested working with https://github.com/meta-llama/llama-stack-client-swift/pull/24

passing together api key in remote inference; readme update

---

examples/agents/e2e_loop_with_client_tools.py
examples/agents/hello.py
examples/agents/inflation.py
examples/agents/podcast_transcript.py
examples/agents/rag_as_attachments.py
examples/agents/rag_with_vector_db.py

chore: simplify imports
